spring.application.name=bazaarhub-api
server.port=8082

# PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/bazaar-hub
spring.datasource.url=jdbc:postgresql://db:5432/bazaar-hub
spring.datasource.username=bazaar-hub-user
spring.datasource.password=secret
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect